import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Note App",
  description: "Generated by Sutanu Bera",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <main>{children}</main>
        <Toaster
          position="top-right"
          toastOptions={{
            style: {
              borderRadius: "8px",
              padding: "12px",
              color: "#fff",
              fontWeight: "500",
            },
          }}
        />
      </body>
    </html>
  );
}
