import type { Metadata } from "next";
// import { Toaster } from "@/components/ui/sonner"
import "./globals.css";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <main>{children}</main>
        <Toaster
          position="top-right"
          toastOptions={{
            style: {
              borderRadius: "8px",
              padding: "12px",
              color: "#fff",
              fontWeight: "500",
            },
          }}
        />
      </body>
      {/* <script src="https://accounts.google.com/gsi/client" async defer></script> */}
    </html>
  );
}
